name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2"
          dune-cache: true
          opam-depext: true

      - name: Build
        run: opam install . --with-test --yes

      - name: Test
        run: opam exec -- dune test
